const CardioidCaseDefaults = Object.freeze({
    pointCount: 250,
    multiplier: 0,
    multiplierSpeed: 0,
    lineWidth: 1.85,
    lineAlpha: 0.4,
    pointRadius: 1.1,
    showPoints: false,
    showHud: true,
    integersOnly: false,
    colorMode: 'angle',
    renderMode: 'light',
    sortMode: 'off',
    sortingStatus: 'idle',
    sortSpeed: 150,
    sortProgress: 0,
    sortPlan: null,
    sortSignature: '',
    sortLockedState: null,
    sortPanelPosition: null,
    sortPanelDrag: null,
    shuffleNonce: 0,
    shuffleOrder: null,
    shuffleSignature: '',
    shuffleFlash: 0,
    shuffleAnimation: null,
    rotation: -Math.PI / 2,
    circleBulge: 0,
    learningMode: 'off',
    classicTargets: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    classicIndex: 0,
    classicDuration: 5.0,
    classicTimer: 0,
    ultimateTargets: [2, 2.1, 1.618, 2.5, 3, 3.14159, 3.5, 4, 5, 8, 13, 21, 34, 55, 67, 89, 99],
    ultimateIndex: 0,
    ultimateTimer: 0,
    ultimateDuration: 5.0,
    mirrorTargets: [2.5, 3.5, 4.5, 6.66, 13.13, 181, 181.5, 359, 359.7],
    mirrorIndex: 0,
    mirrorTimer: 0,
    mirrorDuration: 5.0,
    learnFixedM: 0,
    learnN: 0,
    nRampSlowRate: 12,
    nRampFastRate: 220,
    nRampSwitchN: 120,
    nRampMaxN: 1200,
    mRampFixedN: 420,
    mRampRate: 0.7,
    mRampAccel: 0.035,
    mRampEffectiveRate: 0.7,
    snapRate: 0.45,
    demoIndex: 0,
    demoAuto: true,
    demoRate: 4.0,
    isPaused: false
});
